services:
  frontend:
    container_name: front_end
    build:
      context: .
      target: Frontend
    ports:
      - "5500:5500"
    volumes:
      - ./Frontend:/usr/app/
      - /usr/app/node_modules  # ホストのnode_modulesを除外
    command: sh -c "npm install && npm run dev"

  backend:
    container_name: back_end
    build:
      context: .
      target: Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/usr/app/
      - /usr/app/node_modules  # ホストのnode_modulesを除外
    command: sh -c "npm install && node app.js"

  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      TZ: ${TIME_ZONE}
    ports:
      - "3306:3306"