services:
  frontend:
    init: true
    stdin_open: true
    container_name: Frontend
    build:
      context: .
      target: Frontend
    ports:
      - "5500:5500"
    # volumes:
    #   - ./Frontend:/usr/app/
    command: npm run dev

  backend:
    init: true
    stdin_open: true
    container_name: Backend
    build:
      context: .
      target: Backend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./Backend:/usr/app/
    command: node app.js

  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      TZ: ${TIME_ZONE}
    ports:
      - "3306:3306"
