CREATE DATABASE TICKETSYSTEM CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE TICKETSYSTEM;

CREATE TABLE ORDER(ORDER_NUMBER VARCHAR(4), PRODUCT_NAME VARCHAR(30), PRODUCT_QUANTITY INT(10) ,CHARACTER SET utf8mb4);

INSERT INTO ADMIN_USER (ORDER_NUMBER, PRODUCT_NAME, PRODUCT_QUANTITY) VALUES ("100","PRODUCT1", 1);