CREATE DATABASE TICKETSYSTEM CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE TICKETSYSTEM;

CREATE TABLE ORDERS (
    ORDER_NUMBER VARCHAR(10),
    PRODUCT_NAME VARCHAR(30),
    PRODUCT_QUANTITY INT,
    ADD_BEEF BOOLEAN,
    ADD_EGG BOOLEAN
) CHARACTER SET utf8mb4;

INSERT INTO `ORDERS` (ORDER_NUMBER, PRODUCT_NAME, PRODUCT_QUANTITY, ADD_BEEF, ADD_EGG) VALUES ("100", "PRODUCT1", 1, FALSE, FALSE);