CREATE DATABASE TICKETSYSTEM CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE TICKETSYSTEM;

CREATE TABLE ORDERS (
    ORDER_NUMBER VARCHAR(10),
    PRODUCT_NAME VARCHAR(30),
    PRODUCT_QUANTITY INT
) CHARACTER SET utf8mb4;

INSERT INTO `ORDER` (ORDER_NUMBER, PRODUCT_NAME, PRODUCT_QUANTITY) 
VALUES ("100", "PRODUCT1", 1);